### ISSUE TITLE
Change the EditText in NoteActivity.java to Toolbar title upon losing focus

### ISSUE THREAD

**Issue by GadgyRoid** [plafue/writeily-pro#149]
I think that making the title of the file that the user enters into the `EditText` into a `Toolbar` title would make the app look so much more beautiful! 

I have already implemented this, and I was wondering if I could submit a commit to add this enhancement. 

The app would look like this after the enhancement is added: 

![screenshot_2015-10-15-13-02-02](https://cloud.githubusercontent.com/assets/4739649/10507297/26cba940-733d-11e5-917e-4ed7e1c0461c.png)
![screenshot_2015-10-15-13-02-10](https://cloud.githubusercontent.com/assets/4739649/10507296/26c8d18e-733d-11e5-94fc-282f858e00ee.png)

**Comment by plafue-soundcloud** [comment]
Sure! create a pull request :)

**Comment by plafue** [comment]
Sure! create a pull request :)
