### ISSUE TITLE
Set up distribution on F-Droid

### ISSUE THREAD

**Issue by patcon** [plafue/writeily-pro#39]
I'd do this one. Feel free to assign to me if you want to add me as a read-only contributor

**Comment by patcon** [comment]
https://f-droid.org/forums/topic/writeily-pro/

**Comment by jffrymrtn** [comment]
@patcon sweet! let me know fi you need anything else. I added the license and readme just now

**Comment by patcon** [comment]
I think we're in line with the [inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy) after we add a license, but are there any [anti-features](https://f-droid.org/wiki/page/Antifeatures) we should flag in our metadata? Thinking mainly tracking or non-free (ie. fully FOSS-licenses) deps?

**Comment by jffrymrtn** [comment]
@patcon no tracking on the app, not even Google Analytics. As for any libraries I'm using this to parse Markdown: https://github.com/commonsguy/cwac-anddown

A question: will I need to publish to the F-Droid store in addition to the Play Store on every update?

**Comment by patcon** [comment]
Nope part of what they do is build it from source. So you just tell it how you tag, and when one of those tags appears, it builds, signs with the server's key, and makes it available. Them building it from the public source is a big part of why f-droid is special :)

(I think they now support allowing a signature from the author if we make the builds deterministic -- so it the binary created by you locally and the server is byte-for-byte identitcal, then you can supply your signature beyond just the build server's)

**Comment by patcon** [comment]
(I'll sort out how to set config their builds once I read the docs and submit a PR to their metadata repo)

**Comment by jffrymrtn** [comment]
Nice! That's good to hear then

**Comment by patcon** [comment]
Hm. So if you're set on adding Drive support, I might need to ask the F-Droid guys about it. That's a non-free app that it's giving access to its perms, so that might be a conflict. You're still planning on having one app, right? Like not a "Standard" and "Cloudless" version with minimal extra perms?

**Comment by jffrymrtn** [comment]
@patcon nah, I actually just closed that issue. Sync is hard enough. If i were to do one, it would be Dropbox since its the most common (I assume Dropbox is fine, right?). If Dropbox isn't, then hm...

**Comment by patcon** [comment]
Hm. Seems it won't work because the api keys would need to be in the public repo:
https://f-droid.org/repository/browse/?fdfilter=dropbox&fdid=com.matburt.mobileorg

The "other sync methods" that work are not SaaS-related:
https://play.google.com/store/apps/details?id=com.matburt.mobileorg

I'll ask in IRC

**Comment by patcon** [comment]
Yeah, and it looks like Simpletask maybe created its cloudless version specifically for f-droid:
https://f-droid.org/forums/topic/simpletask-cloudless/

**Comment by jffrymrtn** [comment]
@patcon that's true too, didn't think of the keys/secrets. Right now, I'm not even planning to do sync for a while, but it probably wouldn't make sense to limit it.

I do keep on planning to maintain the original Writeily and keep it on the Play Store. In a sense, that one could be the "cloudless" version...

**Comment by patcon** [comment]
but the keys aren't technically a secret right? Hm. Just went on a research adventure and this was what I was remembering: https://stackoverflow.com/questions/17196160/how-to-develop-secure-dropbox-browser-client

So any android app using oauth has keys that can technically be stolen if the app is decompiled. The only risk is impersonation and confusion. So we can keep them in source, so long as f-droid guys are cool with it

**Comment by patcon** [comment]
OK, I think we're good even when we want to add a sync service. We'd just add an anti-feature flag to the metadata.

IRC ref: https://botbot.me/freenode/fdroid/2015-01-18/?msg=29865015&page=1

**Comment by jffrymrtn** [comment]
@patcon alright, though I don't think having the keys public is a good idea. I think the biggest risk is having other devs take the key and use it for their own app like you said. This shouldn't be a problem in the meantime though, as I don't have immediate plans for sync :p

**Comment by patcon** [comment]
:+1:

**Comment by patcon** [comment]
OK, so I've got a local build server set up for testing, and I think I need your input on certain process-related metadata settings:

https://f-droid.org/manual/html_node/Update-Check-Mode.html#Update-Check-Mode

Any thoughts on what mode fits how you operate?

**Comment by jffrymrtn** [comment]
Looks like Tags is the best fit. Though not clear if it's looking at Git Tags for the version update, or in the AndroidManifest (because my app has the version info in another file, build.gradle)

**Comment by patcon** [comment]
Yeah, I'm running into build issues in my local builder VM, so I'll watch for your changes before trying again. I'll also compare it to a properly building app on f-droid later tonight or tomorrow. Thanks Jeff!

**Comment by jffrymrtn** [comment]
I just moved the versionCode and info to the AndroidManifest. Hopefully this fixes the errors that came up in your VM? Let me know!

**Comment by krt16s** [comment]
I merged a build recipe into fdroid. However, while it builds on my local setup, it might fail on the build server. Let's wait...

Some things I have noticed:
* Jar files should not be used within a git repo: https://github.com/jffrymrtn/writeily-pro/pull/86
* We scan an clean the directoy for binaries, so we have to generate the native libs and package them before running the build. Currently we do `ndk-build && gradle packageNativeLibs` in app/libs/anddown. Shouldn't those steps be executed within the actual build (... and thus removing .so and .jar files from the repo completly)?

**Comment by jffrymrtn** [comment]
I merged your PR for removing the jar dependency. I wonder if it's built on F-Droid? IIRC someone was able to download it there (not sure who/when though).

**Comment by plafue** [comment]
+1 about not pushing binaries (besides assets) to the repo. Maybe it's a good opportunity to change to bypass and resolve the dependency through gradle.

**Comment by krt16s** [comment]
Yes, it's on fdroid. I replaced the jar file on our side for 1.1.1 and 1.2.0 should build with no changes (stripping jars and building native libs from source) tomorrow.

https://f-droid.org/repository/browse/?fdid=me.writeily.pro

**Comment by plafue** [comment]
Heads up about  #99. It seems to build properly on my machine. @krt16s I'd appreciate your feedback... The gradle dependency seems to include native libs for most relevant architectures (besides MIPS)

**Comment by plafue** [comment]
Building after repository transfer seems to work without problems, and without any other additional steps than running gradle build.
