### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by martinjeffrey** [plafue/writeily-pro#43]

**Comment by Minty123** [comment]
+1

**Comment by jeby** [comment]
Yes please!!

**Comment by tedthqme** [comment]
[This widget](https://github.com/tjmolinski/crushr) might be of use/inspiration.

![unnamed](https://cloud.githubusercontent.com/assets/11886052/7095498/fe96ab92-df98-11e4-9530-f1f0bfc97fcb.png)

**Comment by jffrymrtn** [comment]
Working on this now. I'm focusing on this for the version 1.3 release.

**Comment by plafue** [comment]
Sooo, how is the widget coming along? Any teaser screenshots?

**Comment by jffrymrtn** [comment]
Going great! I think I'm going to make it show the top 10 most recently edited files. I was initially going to show the home folder, but I don't think widget works well with browsing directories. Once that's done, some finalizations on design, then I'll post screenies here ;).

**Comment by plafue** [comment]
... or maybe let the user select which folder to use? the folder picker is already there... In any case, cool thing :)

**Comment by plafue** [comment]
Pretty decent support landed with 5606eaa5d2 so i'm closing this by now. Further improvements will be done in the future
